name: zazen_timer
description: A Wear OS zazen timer built with Flutter.
publish_to: "none"

version: 0.3.1+4

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_slidable: ^3.1.1
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.2
  wakelock_plus: ^1.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/logo_v2.png

flutter_launcher_icons:
  android: true
  image_path: "assets/images/logo_v2.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/logo_v2.png"

